#!/bin/bash

# logrotate 설정 배치
install_logrotate_config() {
  LOGROTATE_CONF_PATH="/etc/logrotate.d/pulseone_collector"
  if [ ! -f "$LOGROTATE_CONF_PATH" ]; then
    echo "설정 배포: logrotate 설정 생성"

    cat <<EOF > "$LOGROTATE_CONF_PATH"
/opt/pulseone/logs/**/*.log {
    daily
    rotate 14
    missingok
    notifempty
    compress
    delaycompress
    dateext
    copytruncate
    sharedscripts
    postrotate
        :
    endscript
}
EOF
    chmod 644 "$LOGROTATE_CONF_PATH"
  else
    echo "logrotate 설정은 이미 존재함"
  fi
}
