FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

# MinGW with POSIX thread model
RUN apt-get update && apt-get install -y \
    gcc-mingw-w64-x86-64-posix \
    g++-mingw-w64-x86-64-posix \
    mingw-w64-tools \
    make \
    && rm -rf /var/lib/apt/lists/*

# POSIX 스레드 모델 사용
RUN update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix && \
    update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix

WORKDIR /src
