# 초간단 Makefile - 에러 최소화
CXX = g++
CXXFLAGS = -std=c++17 -g -O1
INCLUDES = -I../include
LIBS = -lpthread -lsqlite3
TEST_LIBS = -lgtest -lgtest_main -pthread

# 컴파일과 실행을 한 번에
test-minimal:
	@echo "Compiling minimal test..."
	@mkdir -p obj bin
	@$(CXX) $(CXXFLAGS) $(INCLUDES) -c ../src/Utils/ConfigManager.cpp -o obj/ConfigManager.o
	@$(CXX) $(CXXFLAGS) $(INCLUDES) -c test_minimal_fixed.cpp -o obj/test_minimal_fixed.o
	@$(CXX) obj/ConfigManager.o obj/test_minimal_fixed.o $(TEST_LIBS) $(LIBS) -o bin/test_minimal_fixed
	@echo "Running minimal test..."
	@./bin/test_minimal_fixed

clean:
	@rm -rf obj bin

.PHONY: test-minimal clean