// Country codes — display names are loaded via i18n (manufacturers.countries.{code})
// Usage: t(`countries.${country.code}`, { ns: 'manufacturers' })
export const COUNTRIES = [
    { code: 'AE' },
    { code: 'AT' },
    { code: 'AU' },
    { code: 'BE' },
    { code: 'BR' },
    { code: 'CA' },
    { code: 'CH' },
    { code: 'CN' },
    { code: 'CZ' },
    { code: 'DE' },
    { code: 'DK' },
    { code: 'ES' },
    { code: 'FI' },
    { code: 'FR' },
    { code: 'GB' },
    { code: 'GR' },
    { code: 'HU' },
    { code: 'ID' },
    { code: 'IE' },
    { code: 'IL' },
    { code: 'IN' },
    { code: 'IT' },
    { code: 'JP' },
    { code: 'KR' },
    { code: 'LU' },
    { code: 'MX' },
    { code: 'MY' },
    { code: 'NL' },
    { code: 'NO' },
    { code: 'PH' },
    { code: 'PL' },
    { code: 'PT' },
    { code: 'RU' },
    { code: 'SA' },
    { code: 'SE' },
    { code: 'SG' },
    { code: 'TH' },
    { code: 'TR' },
    { code: 'TW' },
    { code: 'US' },
    { code: 'VN' },
    { code: 'ZA' },
];

// Legacy mapping: old stored names → country code (for DB migration tolerance)
export const COUNTRY_NAME_TO_CODE: Record<string, string> = {
    // Korean
    '대한민국': 'KR', '한국': 'KR',
    '미국': 'US',
    '일본': 'JP',
    '중국': 'CN',
    '독일': 'DE',
    '영국': 'GB',
    '프랑스': 'FR',
    '캐나다': 'CA',
    '호주': 'AU',
    // English legacy
    'south korea': 'KR', 'korea': 'KR', 'republic of korea': 'KR',
    'usa': 'US', 'united states': 'US', 'america': 'US',
    'japan': 'JP',
    'china': 'CN',
    'germany': 'DE',
    'uk': 'GB', 'united kingdom': 'GB', 'england': 'GB',
    'france': 'FR',
    'canada': 'CA',
    'australia': 'AU',
    'taiwan': 'TW',
};
