FROM ubuntu:22.04
RUN apt-get update && apt-get install -y build-essential cmake git libsqlite3-dev libcurl4-openssl-dev libssl-dev uuid-dev nlohmann-json3-dev pkg-config
RUN git clone --depth 1 --branch bacnet-stack-1.3.8 https://github.com/bacnet-stack/bacnet-stack.git /tmp/bacnet-stack && \
    cd /tmp/bacnet-stack && cmake -Bbuild -DBACNET_STACK_BUILD_APPS=OFF . && cmake --build build/ --target install && rm -rf /tmp/bacnet-stack
RUN git clone --depth 1 --branch v1.2.0 https://github.com/redis/hiredis.git /tmp/hiredis && \
    cd /tmp/hiredis && make && make install && rm -rf /tmp/hiredis
RUN git clone --depth 1 --branch v1.3.13 https://github.com/eclipse/paho.mqtt.c.git /tmp/paho.mqtt.c && \
    cd /tmp/paho.mqtt.c && cmake -Bbuild -DPAHO_ENABLE_TESTING=OFF -DPAHO_BUILD_STATIC=ON -DPAHO_WITH_SSL=ON . && cmake --build build/ --target install && rm -rf /tmp/paho.mqtt.c
RUN git clone --depth 1 --branch v1.3.2 https://github.com/eclipse/paho.mqtt.cpp.git /tmp/paho.mqtt.cpp && \
    cd /tmp/paho.mqtt.cpp && cmake -Bbuild -DPAHO_BUILD_STATIC=ON -DPAHO_BUILD_DOCUMENTATION=OFF . && cmake --build build/ --target install && rm -rf /tmp/paho.mqtt.cpp
WORKDIR /src
