name: Run Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Print working directory and backend contents
        run: |
          echo "📁 CURRENT DIR: $(pwd)"
          echo "📂 Root:"
          ls -al
          echo "📂 Backend:"
          ls -al ./backend

      - name: Install dependencies in backend
        working-directory: ./backend
        run: npm install

      - name: Run backend tests
        working-directory: ./backend
        env:
          NODE_PATH: .
        run: npm test || echo "Backend tests failed"
